# Generated by Django 5.2.8 on 2025-12-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-score']},
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='date_played',
        ),
    ]
